[cog]
Translation_ribosomal_structure_biogenesis = ["foo"]
RNA_processing_and_modification = ["foo"]
Transcription = ["GO:0032774", "GO:0006350"]
Replication_recombination_repair = ["foo"]
Chromatin_structure_and_dynamics = ["foo"]
Cell_cycle_control_cell_division_chromosome_partitioning = ["foo"]
Nuclear_structure = ["foo"]
Defense_mechanisms = ["foo"]
Signal_transduction_mechanisms = ["foo"]
Cell_wall_membrane_envelope_biogenesis = ["foo"]
Cell_motility = ["foo"]
Cytoskeleton = ["GO:0061640", "GO:0008092"]
Extracellular_structures = ["foo"]
Intracellular_trafficking_secretion_and_vesicular_transport = ["foo"]
Posttranslational_modification_protein_turnover_chaperones = ["foo"]
Energy_production_and_conversion = ["foo"]
Carbohydrate_transport_and_metabolism = ["foo"]
Amino_acid_transport_and_metabolism = ["foo"]
Nucleotide_transport_and_metabolism = ["foo"]
Coenzyme_transport_and_metabolism = ["foo"]
Lipid_transport_and_metabolism = ["foo"]
Inorganic_ion_transport_and_metabolism = ["foo"]
Secondary_metabolites_biosynthesis_transport_and_catabolism = ["foo"]
General_function_prediction_only = ["foo"]
Function_unknown = ["foo"]

[toxins]
