[cog_categories]
j = "Translation, ribosomal structure, and biogenesis"
a = "RNA processing and modification"
k = "Transcription"
l = "Replication, recombination, and repair"
b = "Chromatin structure and dynamics"
d = "Cell cycle control, cell division, chromosome partitioning"
y = "Nuclear structure"
v = "Defense mechanisms"
t = "Signal transduction mechanisms"
m = "Cell wall/membrane/envelope biogenesis"
n = "Cell motility"
z = "Cytoskeleton"
w = "Extracellular structures"
u = "Intracellular trafficking, secretion, and vesicular transport"
o = "Posttranslational modification, protein turnover, chaperones"
c = "Energy production and conversion"
g = "Carbohydrate transport and metabolism"
e = "Amino acid transport and metabolism"
f = "Nucleotide transport and metabolism"
h = "Coenzyme transport and metabolism"
i = "Lipid transport and metabolism"
p = "Inorganic ion transport and metabolism"
q = "Secondary metabolites biosynthesis, transport, and catabolism"
r = "General function prediction only"
s = "Function unknown"

[cog]
j = ["foo"]
a = ["foo"]
k = ["GO:0032774", "GO:0006350"]
l = ["foo"]
b = ["foo"]
d = ["foo"]
y = ["foo"]
v = ["foo"]
t = ["foo"]
m = ["foo"]
n = ["foo"]
z = ["GO:0061640", "GO:0008092"]
w = ["foo"]
u = ["foo"]
o = ["foo"]
c = ["foo"]
g = ["foo"]
e = ["foo"]
f = ["foo"]
h = ["foo"]
i = ["foo"]
p = ["foo"]
q = ["foo"]
r = ["foo"]
s = ["foo"]

[header_names]

[header_names.cog]
s = ["uncharacterized", "hypothetical", "predicted", "putative", "unnamed"]

[header_names.toxins]
c_type_lectin = ["c-type lectin"]
serine_protease = ["venom serine protease"]
CRISP = ["cysteine-rich"]
hemolysin = ["hemolysin", "haemolysin"]
neurotoxin = ["scoloptoxin", "latrotoxin", "conotoxin", "secapin"]
metalloprotease = [
    "metalloproteinase",
    "metallopeptidase",
    "metalloendopeptidase",
    "serralysin",
    "disintegrin",
    "reprolysin",
]
jft = ["cftx"]
pore_forming = ["neoverrucotoxin", "porin"]
pesticidal_crystal = ["Pesticidal crystal"]
phospholipase = []
enterotoxin = []
natriuretic = []
nerve_growth_factor = []
amino_acid_oxidase = []
nucleotidase = []


[toxins]
