[cog_categories]
j = "Translation, ribosomal structure, and biogenesis"
a = "RNA processing and modification"
k = "Transcription"
l = "Replication, recombination, and repair"
b = "Chromatin structure and dynamics"
d = "Cell cycle control, cell division, chromosome partitioning"
y = "Nuclear structure"
v = "Defense mechanisms"
t = "Signal transduction mechanisms"
m = "Cell wall/membrane/envelope biogenesis"
n = "Cell motility"
z = "Cytoskeleton"
w = "Extracellular structures"
u = "Intracellular trafficking, secretion, and vesicular transport"
o = "Posttranslational modification, protein turnover, chaperones"
c = "Energy production and conversion"
g = "Carbohydrate transport and metabolism"
e = "Amino acid transport and metabolism"
f = "Nucleotide transport and metabolism"
h = "Coenzyme transport and metabolism"
i = "Lipid transport and metabolism"
p = "Inorganic ion transport and metabolism"
q = "Secondary metabolites biosynthesis, transport, and catabolism"
# r = "General function prediction only"
# s = "Function unknown"


[cog]
j = [
    "GO:0006412", # BP: Translation
    "GO:0045182", # MF: translation regulator activity
    "GO:0033750", # BP: ribosome localization
    "GO:0005840", # CC: ribosome
    "GO:0042254", # ribosome biogenesis
    "GO:0019843", # MF: rRNA binding"
]
a = [ # RNA processing and modification
    "GO:0006396", # BP: RNA processing, note this is
    # a child of RNA biosynthetic process
    "GO:00160",   # BP: RNA metabolic process
    "GO:0004540", # MF: RNA nuclease activity
    "GO:0034518", # CC: RNA cap binding complex
    "GO:0030555", # MF: RNA modification guide activity
    "GO:0003723", # MF: RNA binding
    "GO:0030532", # CC small nuclear ribonucleoprotein complex
]
# Must make sure that if something is defined here, it will be ignored, so that its children won't get mapped into another category
k = [ # Transcription
    "GO:0032774", # BP: RNA biosynthetic process
    "GO:0070063", # MF: RNA polymerase binding
    "GO:0097747", # MF: RNA polymerase activity
    "GO:0005667", # CC: transcription regulator complex
    "GO:0140110", # MF transcription regulator activity"
    "GO:0030880", # CC: RNA polymerase complex
    "GO:0008023", # CC: transcription elongation factor complex"
    "GO:0000172", # ribonuclease MRP complex
]
l = [ # Replication, recombination, and repair
    "GO:0042575", # CC DNA polymerase complex
    "GO:0030894", # CC replisome
    "GO:0044796", # CC DNA polymerase processivity factor complex
    "GO:0031261", # CC DNA replication preinitiation complex
    "GO:0044777", # CC single-stranded DNA-binding protein complex
    "GO:0097047", # CC DNA replication termination region
    "GO:0003688", # MF DNA replication origin binding
    "GO:0030337", # MF DNA polymerase processivity factor activity
    "GO:0003887", # MF DNA-directed DNA polymerase activity
    "GO:0003896", # MF DNA primase activity
    "GO:0006275", # BP regulation of DNA replication
    "GO:0006260", # BP DNA replication
    "GO:0031570", # BP DNA integrity checkpoint signaling
    "GO:0006261", # BP DNA-templated DNA replication
    "GO:0006281", # BP DNA repair
    "GO:0071897", # BP DNA biosynthetic process
    "GO:0045005", # BP DNA-templated DNA replication maintenance of fidelity
    "GO:0032404", # MF mismatch repair complex binding
    "GO:0003906", # MF DNA-(apurinic or apyrimidinic site) endonuclease activity
    "GO:0000109", # CC nucleotide-excision repair complex
    "GO:1990391", # CC DNA repair complex
    "GO:0032300", # CC mismatch repair complex
    "GO:0006310", # BP DNA recombination
    "GO:0000018", # BP regulation of DNA recombination
]
b = [ # Chromatin structure and dynamics
    "GO:0006325",    # BP chromatin organization
    "GO:1902275",    # BP regulation of chromatin organization
    "GO:0005876",    # CC spindle microtubule
    "GO:GO:0004407", # MF histone deacetylase activity
    "GO:GO:0003682", # MF chromatin binding
    "GO:GO:0035561", # BP regulation of chromatin binding
    "GO:GO:0000785", # CC chromatin
    "GO:GO:0030874", # CC nucleolar chromatin
    "GO:GO:0097346", # CC INO80-type complex
    "GO:GO:0016581", # CC NuRD complex
]
d = [ # Cell cycle control, cell division, chromosome partitioning
    "GO:0051302", # BP regulation of cell division
    "GO:0051726", # BP regulation of cell cycle
    "GO:0022402", # BP cell cycle process
    "GO:0010564", # BP regulation of cell cycle process
    "GO:0000075", # BP cell cycle checkpoint signaling
    "GO:0022403", # BP cell cycle phase
    "GO:0005713", # CC recombination nodule
    "GO:0007051", # BP spindle organization
    "GO:0030332", # MF cyclin binding
    "GO:0016538", # MF cyclin-dependent protein serine/threonine kinase regulator activity
    "GO:0000940", # CC outer kinetochore
    "GO:0008278", # CC cohesin complex
    "GO:0005819", # CC spindle
    "GO:0031518", # CC CBF3 complex
    "GO:0000796", # CC condensin complex
    "GO:0042729", # CC DASH complex
    "GO:0000776", # CC kinetochore
    "GO:1990941", # CC mitotic spindle kinetochore microtubule
    "GO:0000280", # BP nuclear division
]
y = [ # Nuclear structure
    "foo",
]
v = [ # Defense mechanisms
    "foo",
]
t = [ # Signal transduction mechanisms
    "foo",
]
m = [ # Cell wall/membrane/envelope biogenesis
    "foo",
]
n = [ # Cell motility
    "foo",
]
z = [ # Cytoskeleton
    "GO:0061640",
    "GO:0008092",
]
w = [ # Extracellular structures
    "foo",
]
u = [ # Intracellular trafficking, secretion, and vesicular transport
    "foo",
]
o = [ # Posttranslational modification, protein turnover, chaperones
    "foo",
]
c = [ # Energy production and conversion
    "foo",
]
g = [ # Carbohydrate transport and metabolism
    "foo",
]
e = [ # Amino acid transport and metabolism
    "foo",
]
f = [ # Nucleotide transport and metabolism
    "foo",
]
h = [ # Coenzyme transport and metabolism
    "foo",
]
i = [ # Lipid transport and metabolism
    "foo",
]
p = [ # Inorganic ion transport and metabolism
    "foo",
]
q = [ # Secondary metabolites biosynthesis, transport, and catabolism
    "foo",
]
venom_component = [""]
# Anything uncategorized goes to function "Other"
# And no GO terms means "Unknown"

[header_names]
[header_names.cog]
j = [
    "ribosomal",
    "elongation factor tu",
    "eukaryotic translation initiation factor",
]
a = ["rna helicase", "rnase", "cleavage and polyadenylation specificity factor"]
m = ["cell envelope"]
n = ["axoneme-associated", "cilia"]
z = [
    "microtubule",
    "dynein",
    "beta-actin",
    "beta-centractin",
    "myosin",
    "tubulin",
    "actin",
    "gelsolin",
    "laminin",
    "gelsolin-like",
    "centractin",
]
w = ["fibrillin", "outer membrane protein", "collagen", "cadherin"]
u = ["dynamin", "coatomer", "clathrin"]
l = [
    "dna polymerase",
    "dna ligase",
    "dna double-strand break repair",
    "dna primase",
    "helicase",
]
t = [
    "receptor protein-tyrosine kinase",
    "fibroblast growth factor receptor",
    "calmodulin",
    "calcium/calmodulin",
    "ras-like",
    "contactin",
    "ras-related",
    "wnt",
    "g-protein coupled receptor",
]
k = ["rna polymerase"]
d = [
    "cell cycle",
    "cell division control",
    "spindle",
    "cyclin-dependent kinase",
]
v = ["thioredoxin", "complement c3", "cytochrome p450"]
y = ["histone", "nuclear pore complex"]
o = [
    "e3 ubiquitin",
    "chaperone",
    "autophagy",
    "proteasome",
    "protease",
    "endoprotease",
    "heat shock",
    "hsp",
    "chaperonin",
    "calnexin",
]
c = [
    "malate",
    "dehydrogenase",
    "fumarate",
    "hydratase",
    "glycogen",
    "phosphorylase",
    "atp",
    "synthase",
    "hexokinase",
    "phosphofructokinase",
    "isocitrate",
    "dehydrogenase",
    "cytochrome c oxidase",
    "aconitate hydratase",
    "citrate synthase",
]
g = ["lectin"]
e = [
    "amino",
    "acid",
    "transporter",
    "glutamate",
    "dehydrogenase",
    "argininosuccinate lyase",
    "asparagine synthetase",
    "aspartate aminotransferase",
    "glutamine synthetase",
    "peptidase",
]
f = ["rna-binding", "exonuclease"]
h = [
    "acetyl-coenzyme a synthetase",
    "glutathione synthase",
    "glutathione synthetase",
    "acyl-coenzyme a",
    "aldehyde dehydrogenase",
]
i = ["scramblase"]
venom_component = [
    "toxin",
    "venom",
    "porin",
    "phospholipase a2",
    "pesticidal crystal protein",
    "disintegrin",
    "metalloproteinase",
]
s = ["uncharacterized", "hypothetical", "predicted", "putative", "unnamed"]

[header_names.toxins]
c_type_lectin = ["c-type lectin"]
serine_protease = ["venom serine protease"]
CRISP = ["cysteine-rich"]
hemolysin = ["hemolysin", "haemolysin"]
neurotoxin = ["scoloptoxin", "latrotoxin", "conotoxin", "secapin"]
metalloprotease = [
    "metalloproteinase",
    "metallopeptidase",
    "metalloendopeptidase",
    "serralysin",
    "disintegrin",
    "reprolysin",
]
jft = ["cftx"]
pore_forming = ["neoverrucotoxin", "porin"]
pesticidal_crystal = ["Pesticidal crystal"]
phospholipase = []
enterotoxin = []
natriuretic = []
nerve_growth_factor = []
amino_acid_oxidase = []
nucleotidase = []

[toxins]
hemolysin = [
    "GO:0044179",
    "GO:0044468", # envenomation resulting in modulation of blood coagulation in another organism
    "GO:0044483", # envenomation resulting in impairment of hemostasis in another organism:
    "GO:0044358", # envenomation resulting in hemorrhagic damage in another organism
]
c_type_lectin = [
    "GO:0001862",
    "GO:0002772", # inhibitory C-type lectin receptor signaling pathway
    "GO:0002223", # stimulatory C-type lectin receptor signaling pathway
]
serine_protease = [
    "GO:0001648", # proteinase-activated receptor activity
    "GO:0097180", # serine protease inhibitor complex
]
CRISP = []
neurotoxin = [
    "GO:0016524", # latrotoxin receptor activity
]
metalloprotease = [
    "GO:0098769", # TIMP family protein binding
    "GO:0071100", # alphaV-beta8 integrin-MMP14-TGFbeta-1 complex
    "GO:1990773", # matrix metallopeptidase secretion
    "GO:1905048", # regulation of metallopeptidase activity
    "GO:1904464", # regulation of matrix metallopeptidase secretion
    "GO:0008237", # metallopeptidase activity
]
jft = []
pore_forming = [
    "GO:0008282", # inward rectifying potassium channel
    "GO:0140911", # pore-forming activity
    "GO:0046931", # pore complex assembly
    "GO:0046930", # pore complex
    "GO:0044471", # envenomation resulting in pore formation in membrane of another organism
    "GO:0072559", # NLRP3 inflammasome complex
]
cardiotoxin = [
    "GO:0044556", # envenomation resulting in negative regulation of heart rate in another organism
]
myotoxin = [
    "GO:0044482", # envenomation resulting in muscle damage in another organism
]
pesticidal_crystal = []
phospholipase = [
    "GO:0004620", # phospholipase activity (covers phospholipase A2)
    "GO:0010517", # regulation of phospholipase activity
]
enterotoxin = []
natriuretic = [
    "GO:0016941", # natriuretic peptide receptor activity
    "GO:0003050", # regulation of systemic arterial blood pressure by atrial natriuretic peptide
]
nerve_growth_factor = [
    "GO:0005163",  # nerve growth factor receptor binding
    "GO:0044487",  # envenomation resulting in modulation of transmission of nerve impulse in another
    "GO:0032898",  # neurotrophin production
    "GO:0032455",  # nerve growth factor processing
    "GO:0005030",  # neurotrophin receptor activity
    " GO:0032899", # regulation of neurotrophin production"
    "GO:0051394",  # regulation of nerve growth factor receptor activity
]
amino_acid_oxidase = []
nucleotidase = [
    "GO:0032903", # nucleotidase activity
]
