---
title: "GO word frequency"
output:
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---


### Check in each ontology
```{r}
info_tb %>%
    filter(ontology == "BP") %>%
    showFrequent(., filter_unwanted = FALSE)
info_tb %>%
    filter(ontology == "MF") %>%
    showFrequent(., filter_unwanted = FALSE)
info_tb %>%
    filter(ontology == "CC") %>%
    showFrequent(., filter_unwanted = FALSE)
```
**Conclusion:** no verbs associated with MF or CC. Only with BP

### `response` terms
```{r}
showFrequent(info_tb, "response")
```
**Conclusion:** main qualifiers are "positive" and "negative"

### `regulation` terms
```{r}
showFrequent(info_tb, "regulation")
```
**Conclusion:** main qualifiers are "positive" and "negative"

### `metabolic` terms
```{r}
showFrequent(info_tb, "metabolic")
metabolic_regulation <- info_tb %>%
    filter(grepl("metabolic", term)) %>%
    mutate(
        has_verb = grepl("positive|negative", term),
        has_regulation = grepl("regulation", term)
    )
metabolic_regulation %>%
    select(has_verb, has_regulation) %>%
    table()
```
**Conclusion:** no verbs associated, those that are are based on regulation

```{r}
showFrequent(info_tb) %>% filter(!word %in% qualifiers)
info_tb %>% filter(grepl("biosynthetic", term))
```
