```{r echo=FALSE, results='hide', message=FALSE, comment=NA}
source("../bin/get_metrics.r")
library(MSnbase)
library(ggpubr)
library(Spectra)
library(DiagrammeR)
plot_mw_dist <- function(combined_table) {
  combined_table %>% ggplot(aes(x = mw, y = engine, fill = engine)) +
    geom_boxplot() +
    theme(
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_text(size = rel(1.3)),
      legend.text = element_text(size = rel(1.3))
    )
}
plot_len_dist <- function(combined_table) {
  combined_table %>% ggplot(aes(x = length, y = engine, fill = engine)) +
    ggridges::geom_density_ridges2() +
    theme(
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_text(size = rel(1.3)),
      legend.text = element_text(size = rel(1.3))
    )
}
```

```{r, echo=FALSE}
args <- c("~/CiCs1.mzML", "../results/CiCs_metrics.tsv")
input <- args[1]
all_data <- openMSfile(input) # This reads all information from the mzml
#   file by default
all_headers <- all_data %>%
  header() %>%
  as_tibble()
tic <- chromatogram(readMSData(input, mode = "onDisk"))
```

```{r, echo=FALSE}
ms1 <- which(all_headers$msLevel == 1)
selected_rt <- all_headers$retentionTime[ms1] / 60 > 40 & all_headers$retentionTime[ms1] / 60 < 45
ms1_all <- all_headers %>%
  filter(msLevel == 1) %>%
  as_tibble()
M <- MSmap(all_data, ms1[selected_rt], 500, 503, 0.05, all_headers, zeroIsNA = TRUE)
svg("3dimensional.svg")
plot3D(M)
dev.off()
```

#### MS/MS spectra

```{r, echo=FALSE}
# Plot spectra
ms2 <- Spectra(input) %>% filterMsLevel(2)
sample <- ms2[1:4]
names <- paste0("Precursor m/z: ", sample$precursorMz)
svg("sample_msms.svg")
plotSpectra(sample, main = names, col = "darkgreen")
dev.off()
```

#### Distribution of identified proteins by engine
```{r, echo=FALSE}
map <- "../results/jellyfish/Databases/seq-header_mappings.tsv"
file_path <- "../results/jellyfish/1-First_pass/Percolator"
all_psms <- get_tables(file_path, TRUE, 1, 0.05, map)
all_proteins <- get_tables(file_path, FALSE, 1, 0.05, map)

# psm_mw_dist <- plot_mw_dist(all_psms)
# psm_len_dist <- plot_len_dist(all_psms)
# psm_mw_len <- ggarrange(psm_len_dist, psm_mw_dist, ncol = 2, nrow = 1,
#   common.legend = TRUE, legend = "right")
# ggsave(
#   plot = psm_mw_len, device = svg,
#   scale = 1, width = 50, height = 20, units = "cm",
#   filename = "./images/len_mw_dist.svg"
# )
#
# protein_mw_dist <- plot_mw_dist(all_proteins)
# ggsave(
#   plot = protein_mw_dist, device = svg,
#   filename = "./images/protein_mw_dist.svg"
# )
# protein_len_dist <- plot_len_dist(all_proteins)
# ggsave(
#   plot = protein_len_dist, device = svg,
#   filename = "./images/protein_len_dist.svg"
# )
```

#### Distribution of identification results
```{r, echo=FALSE}
# Is the difference between distributions statistically significant?
engines <- unique(all_proteins$engine)
engine_combos <- engines %>% combn(2)
engine1 <- vector()
engine2 <- vector()
mw_pvalue <- vector()
len_pvalue <- vector()
for (comb in seq_len(dim(engine_combos)[2])) {
  first <- engine_combos[, comb][1]
  engine1 <- append(engine1, first)
  second <- engine_combos[, comb][2]
  engine2 <- append(engine2, second)
  first_df <- all_psms %>% filter(engine == first)
  second_df <- all_psms %>% filter(engine == second)
  try <- ks.test(first_df$mw, second_df$mw)
  mw_pvalue <- append(mw_pvalue, try$p.value)
  try <- ks.test(first_df$length, second_df$length)
  len_pvalue <- append(len_pvalue, try$p.value)
}
p_df <- data.frame(
  engine1 = engine1, engine2 = engine2,
  mw_p_value = mw_pvalue,
  length_p_value = len_pvalue
)
```

#### Overlap of engines' identified proteins
```{r, echo=FALSE}
id_list <- lapply(engines, function(x) {
  return(filter(all_proteins, engine == x)$id)
}) %>% `names<-`(engines)
svg("engine_intersections.svg")
venn(id_list,
  plotsize = 100, borders = FALSE, box = FALSE,
  ilcs = 1, sncs = 1.5,
  zcolor = "red, blue, green, white, orange, yellow"
)
dev.off()
```
